### ISSUE TITLE
fails to build with Ruby 2.2

### ISSUE THREAD

**Issue by swills** [knu/ruby-bdb#4]
This module fails to build with Ruby 2.2:

```
compiling recnum.c
recnum.c:20:49: warning: implicit declaration of function 'RHASH' is invalid in C99 [-Wimplicit-function-declaration]
    if (rb_hash_aref(argv[argc - 1], sarray) != RHASH(argv[argc - 1])->ifnone) {
                                                ^
recnum.c:20:72: error: member reference type 'int' is not a pointer
    if (rb_hash_aref(argv[argc - 1], sarray) != RHASH(argv[argc - 1])->ifnone) {
                                                ~~~~~~~~~~~~~~~~~~~~~  ^
recnum.c:180:13: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (beg < 0) {
        ~~~ ^ ~
recnum.c:183:13: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
    if (beg < 0) {
        ~~~ ^ ~
recnum.c:747:61: error: member reference type 'int' is not a pointer
        if ((g = rb_hash_aref(f, rb_intern("flags"))) != RHASH(f)->ifnone ||
                                                         ~~~~~~~~  ^
recnum.c:748:63: error: member reference type 'int' is not a pointer
            (g = rb_hash_aref(f, rb_str_new2("flags"))) != RHASH(f)->ifnone) {
                                                           ~~~~~~~~  ^
3 warnings and 3 errors generated.
*** Error code 1

Stop.
```

This is because the RHASH has been hidden in 2.2, see https://bugs.ruby-lang.org/issues/9889
